#!/bin/sh -e

master_path=/opt/buildbot/lsb-master
snapshot_path=/opt/buildbot/ftpdir/pub/lsb/snapshots

sdk_projects="build_env lsbdev-c++ lsbdev-qt lsbdev-qt3"

cd $snapshot_path

for prj in $sdk_projects; do
    rm -rf $prj
    mkdir $prj
done

rm -rf junk
mkdir junk
cd junk

for f in $(ls $master_path/lsb-sdk-devel-*tar.gz | egrep 'devel-[^-]*.tar.gz')
do
    tar xzf $f
    for prj in $sdk_projects; do
	ls sdk-results/$prj/*.rpm | egrep -v src.rpm | \
	    (while read ff; do chmod 644 $ff; mv $ff ../$prj; done)
    done
    rm -rf results
done

if [ -f $master_path/lsb-sdk-devel-x86_64.tar.gz ]; then
    tar xzf $master_path/lsb-sdk-devel-x86_64.tar.gz
    for prj in $sdk_projects; do
	mv sdk-results/$prj/*src.rpm ../$prj
	chmod 644 ../$prj/*src.rpm
    done
fi

cd ..
rm -rf junk
