#!/bin/sh -e

LOCKFILE_PATH=/data/buildbot/update-snapshot.lock
SCRIPT_PATH=$(dirname $0)
TOP_PATH=/data/buildbot/lsb-snapshots
SNAPSHOT_PATH=pub/lsb/snapshots
REPOSITORY_PATH=pub/lsb/repositories
UPLOAD_TARGET=autobuild@spidey.linuxfoundation.org:/srv/ftp

BZR_PROGRESS_BAR=none
FTP_ROOT=$TOP_PATH
BUILD_DEBIAN=yes
DEB_PKG_CACHE=/data/buildbot/debcache-snapshot
LSB_VERSION=snapshot
export BZR_PROGRESS_BAR FTP_ROOT BUILD_DEBIAN DEB_PKG_CACHE LSB_VERSION

echo $$ > $LOCKFILE_PATH.$$ 2>/dev/null || exit 1
ln $LOCKFILE_PATH.$$ $LOCKFILE_PATH 2>/dev/null || {
    kill -0 $(cat $LOCKFILE_PATH) 2> /dev/null || {
	rm -f $LOCKFILE_PATH
    }
    rm -f $LOCKFILE_PATH.$$
    exit 1
}

rm -f $LOCKFILE_PATH.$$

$SCRIPT_PATH/update-snapshot-sdk
$SCRIPT_PATH/update-snapshot-prj

cd $TOP_PATH
bzr checkout http://bzr.linuxfoundation.org/lsb/devel/repogen
cd repogen
make -s snapshot
make -s install-snapshot
cd ..
rm -rf repogen

cd $TOP_PATH/$SNAPSHOT_PATH
rsync -a --delete * $UPLOAD_TARGET/$SNAPSHOT_PATH
cd $TOP_PATH/$REPOSITORY_PATH/yum
rsync -a --delete lsb-snapshot $UPLOAD_TARGET/pub/lsb/repositories/yum
cd $TOP_PATH/$REPOSITORY_PATH/debian
rsync -a --delete pkgs-snapshot $UPLOAD_TARGET/pub/lsb/repositories/debian
cd dists
rsync -a --delete lsb-snapshot $UPLOAD_TARGET/pub/lsb/repositories/debian/dists

rm -f $LOCKFILE_PATH
