#!/bin/sh -e

master_path=/opt/buildbot/lsb-master
snapshot_path=/opt/buildbot/ftpdir/pub/lsb/snapshots

projects="app-checker azov-qt3-tests azov-qt4-tests azov-xml2-tests desktop-test distribution-checker dtk-manager libstdcpp-test lsb-sigchk lsb-setup lsb-xvfb lsbappchk-perl lsbappchk-python lsbappchk-sh lsbappchk lsbsi-tools makelsbpkg olver-core-tests perl-test printing-test python-test qmtest-harness runtime-test t2c-alsa-tests t2c-cpp-tests t2c-desktop-tests t2c-runtime-tests task-pkgs tet-harness xts5-test lsbarchk lsbcmdchk lsbdev-runner lsblibchk lsbpkgchk lsbdynchk lsb-xdg-utils libbat appbat"

mkdir -p $snapshot_path
cd $snapshot_path

for prj in $projects; do
    #echo $prj
    rm -rf $prj
    mkdir $prj
    cd $prj

    for f in $(ls $master_path/$prj-devel-*.tar.gz 2>/dev/null | \
               egrep 'devel-[^-]*.tar.gz')
    do
	tar xzf $f
	ls results/*.rpm 2>/dev/null | egrep -v src.rpm | (while read ff; do chmod 644 $ff; mv $ff .; done) || true
	rm -rf results
    done

    if [ -f $master_path/$prj-devel-x86_64.tar.gz ]; then
        tar xzf $master_path/$prj-devel-x86_64.tar.gz
	if [ $(ls results/*src.rpm 2>/dev/null | wc -l) -gt 0 ]; then
            mv results/*src.rpm .
	    chmod 644 *src.rpm
	fi
        rm -rf results
    fi

    cd ..
done

# Add symlink to appbat tests.
(cd appbat && ln -sf ../../app-battery/tests tests)

# Unpack devchk info.
rm -rf devchk
mkdir devchk
cd devchk

for devchktar in $master_path/devchk-*.tar.gz; do
    pathname=$(basename $devchktar | sed s/devchk-// | sed s/.tar.gz//)
    zcat $devchktar | tar xf -
    mv results $pathname
done

cd ..
