#!/bin/sh -e

master_path=/data/buildbot/master_lsb
snapshot_path=/data/buildbot/lsb-snapshots

sdk_projects="lsbdev-base lsbdev-cc lsbdev-c++ lsbdev-desktop lsbdev-qt lsbdev-qt3"

cd $snapshot_path

for prj in $sdk_projects; do
    rm -rf $prj
    mkdir $prj
done

rm -rf junk
mkdir junk
cd junk

for f in $master_path/lsb-sdk-results-*tar.gz; do
    tar xzf $f
    for prj in $sdk_projects; do
	ls sdk-results/$prj/*.rpm | egrep -v src.rpm | \
	    (while read ff; do mv $ff ../$prj; done)
    done
    rm -rf results
done

if [ -f $master_path/lsb-sdk-results-x86_64.tar.gz ]; then
    tar xzf $master_path/lsb-sdk-results-x86_64.tar.gz
    for prj in $sdk_projects; do
	mv sdk-results/$prj/*src.rpm ../$prj
    done
fi

cd ..
rm -rf junk
